// <auto-generated />
using System;
using Mews.Job.Scheduler.Core.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mews.Job.Scheduler.Core.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(JobSchedulerDbContext))]
    [Migration("20241127094742_AddedExecutorTypeNameValueIndex")]
    partial class AddedExecutorTypeNameValueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mews.Job.Scheduler.Domain.JobExecutions.JobExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatorProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExecutorTypeNameValue")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdaterProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatorProfileId");

                    b.HasIndex("ExecutorTypeNameValue");

                    b.HasIndex("JobId")
                        .HasFilter("([State]=(0))");

                    b.HasIndex("StartUtc");

                    b.HasIndex("UpdaterProfileId");

                    b.HasIndex("JobId", "StartUtc");

                    b.HasIndex("JobId", "State")
                        .HasFilter("([State]=(0))");

                    b.HasIndex("StartUtc", "JobId");

                    b.HasIndex("StartUtc", "State");

                    b.HasIndex("JobId", "State", "IsDeleted")
                        .HasFilter("([IsDeleted]=(0))");

                    b.HasIndex("StartUtc", "ExecutorTypeNameValue", "State");

                    b.ToTable("JobExecution", (string)null);
                });

            modelBuilder.Entity("Mews.Job.Scheduler.Domain.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatorProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("EntityVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasDefaultValue(new byte[] { 0 });

                    b.Property<DateTime?>("ExecutionStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExecutorTypeNameValueNew")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LogVerbosity")
                        .HasColumnType("int");

                    b.Property<string>("MaxExecutionTimeValue")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("NameNew")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Options")
                        .HasColumnType("int");

                    b.Property<string>("PeriodValue")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("PreviousSuccessfulStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ScheduledUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdaterProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("CreatorProfileId");

                    b.HasIndex("UpdaterProfileId");

                    b.HasIndex("Id", "EntityVersion");

                    b.HasIndex("State", "IsDeleted");

                    b.HasIndex("ExecutorTypeNameValueNew", "NameNew", "State");

                    b.HasIndex("StartUtc", "State", "ExecutorTypeNameValueNew", "NameNew")
                        .HasFilter("([IsDeleted]=(0))");

                    b.ToTable("Job", (string)null);
                });

            modelBuilder.Entity("Mews.Job.Scheduler.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d717d2a3-6084-48ab-9143-df5739aae6c0"),
                            Address = "",
                            Email = "john.smith@example.com",
                            Name = "John",
                            Nickname = "johnny",
                            Surname = "Smith"
                        },
                        new
                        {
                            Id = new Guid("55fef0ec-1fb3-4884-999f-de1615a18ae9"),
                            Address = "",
                            Email = "jane.doe@example.com",
                            Name = "Jane",
                            Nickname = "",
                            Surname = "Doe"
                        });
                });

            modelBuilder.Entity("Mews.Job.Scheduler.Domain.JobExecutions.JobExecution", b =>
                {
                    b.HasOne("Mews.Job.Scheduler.Domain.Jobs.Job", "Job")
                        .WithMany("JobExecutions")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Mews.Job.Scheduler.Domain.Jobs.Job", b =>
                {
                    b.Navigation("JobExecutions");
                });
#pragma warning restore 612, 618
        }
    }
}
