// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxManager.EntityFrameworkCore.Data;

#nullable disable

namespace TaxManager.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250602172217_ChangeDateTimeOffsetToDateTime")]
    partial class ChangeDateTimeOffsetToDateTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LegalEnvironmentTaxation", b =>
                {
                    b.Property<Guid>("LegalEnvironmentsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaxationsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LegalEnvironmentsId", "TaxationsId");

                    b.HasIndex("TaxationsId");

                    b.ToTable("LegalEnvironmentTaxation");
                });

            modelBuilder.Entity("SubdivisionTaxation", b =>
                {
                    b.Property<int>("SubdivisionsId")
                        .HasColumnType("int");

                    b.Property<Guid>("TaxationsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SubdivisionsId", "TaxationsId");

                    b.HasIndex("TaxationsId");

                    b.ToTable("SubdivisionTaxation");
                });

            modelBuilder.Entity("TaxManager.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("TaxManager.Domain.Entities.DependentTaxation", b =>
                {
                    b.Property<Guid>("TaxationTaxRateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildTaxationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TaxationTaxRateId", "ChildTaxationId");

                    b.HasIndex("ChildTaxationId");

                    b.ToTable("DependentTaxation");
                });

            modelBuilder.Entity("TaxManager.Domain.Entities.LegalEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<decimal>("DepositTaxRateMode")
                        .HasColumnType("decimal(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LegalEnvironments");
                });

            modelBuilder.Entity("TaxManager.Domain.Entities.Subdivision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Subdivisions");
                });

            modelBuilder.Entity("TaxManager.Domain.Entities.TaxRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TaxRates");
                });

            modelBuilder.Entity("TaxManager.Domain.Entities.Taxation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CountryId");

                    b.ToTable("Taxations");
                });

            modelBuilder.Entity("TaxManager.Domain.Entities.TaxationTaxRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("EndDateTimeZone")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("StartDateTimeZone")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Strategy")
                        .HasColumnType("int");

                    b.Property<int>("TaxRateId")
                        .HasColumnType("int");

                    b.Property<Guid>("TaxationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("ValueType")
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("TaxRateId");

                    b.HasIndex("TaxationId");

                    b.ToTable("TaxationTaxRates");
                });

            modelBuilder.Entity("LegalEnvironmentTaxation", b =>
                {
                    b.HasOne("TaxManager.Domain.Entities.LegalEnvironment", null)
                        .WithMany()
                        .HasForeignKey("LegalEnvironmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxManager.Domain.Entities.Taxation", null)
                        .WithMany()
                        .HasForeignKey("TaxationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubdivisionTaxation", b =>
                {
                    b.HasOne("TaxManager.Domain.Entities.Subdivision", null)
                        .WithMany()
                        .HasForeignKey("SubdivisionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxManager.Domain.Entities.Taxation", null)
                        .WithMany()
                        .HasForeignKey("TaxationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxManager.Domain.Entities.DependentTaxation", b =>
                {
                    b.HasOne("TaxManager.Domain.Entities.Taxation", "ChildTaxation")
                        .WithMany()
                        .HasForeignKey("ChildTaxationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxManager.Domain.Entities.TaxationTaxRate", "TaxationTaxRate")
                        .WithMany("DependentTaxations")
                        .HasForeignKey("TaxationTaxRateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildTaxation");

                    b.Navigation("TaxationTaxRate");
                });

            modelBuilder.Entity("TaxManager.Domain.Entities.Subdivision", b =>
                {
                    b.HasOne("TaxManager.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("TaxManager.Domain.Entities.Taxation", b =>
                {
                    b.HasOne("TaxManager.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("TaxManager.Domain.Entities.TaxationTaxRate", b =>
                {
                    b.HasOne("TaxManager.Domain.Entities.TaxRate", "TaxRate")
                        .WithMany()
                        .HasForeignKey("TaxRateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxManager.Domain.Entities.Taxation", "Taxation")
                        .WithMany("TaxationTaxRates")
                        .HasForeignKey("TaxationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaxRate");

                    b.Navigation("Taxation");
                });

            modelBuilder.Entity("TaxManager.Domain.Entities.Taxation", b =>
                {
                    b.Navigation("TaxationTaxRates");
                });

            modelBuilder.Entity("TaxManager.Domain.Entities.TaxationTaxRate", b =>
                {
                    b.Navigation("DependentTaxations");
                });
#pragma warning restore 612, 618
        }
    }
}
